"""initial

Revision ID: 99c07a23d5e1
Revises: 
Create Date: 2026-07-07 16:27:09.264746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '99c07a23d5e1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('affiliate_clicks', 'clicked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_clicks_offer'), table_name='affiliate_clicks')
    op.drop_constraint(op.f('build_airflow_state_session_id_zone_name_key'), 'build_airflow_state', type_='unique')
    op.create_unique_constraint('build_airflow_state_session_zone_key', 'build_airflow_state', ['session_id', 'zone_name'])
    op.drop_constraint(op.f('build_clearances_session_id_slot_name_key'), 'build_clearances', type_='unique')
    op.create_unique_constraint('build_clearances_session_slot_key', 'build_clearances', ['session_id', 'slot_name'])
    op.execute("ALTER TABLE build_sessions ALTER COLUMN games DROP DEFAULT, "
               "ALTER COLUMN games TYPE JSONB USING to_jsonb(games), "
               "ALTER COLUMN games SET DEFAULT '[]'::jsonb")
    op.alter_column('build_sessions', 'components',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('build_sessions', 'clearances',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('build_sessions', 'airflow_state',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('build_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('build_sessions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.execute("ALTER TABLE case_airflow_zones ALTER COLUMN connects_to DROP DEFAULT, "
               "ALTER COLUMN connects_to TYPE JSONB USING to_jsonb(connects_to), "
               "ALTER COLUMN connects_to SET DEFAULT '[]'::jsonb")
    op.execute("ALTER TABLE case_airflow_zones ALTER COLUMN heat_source_slots DROP DEFAULT, "
               "ALTER COLUMN heat_source_slots TYPE JSONB USING to_jsonb(heat_source_slots), "
               "ALTER COLUMN heat_source_slots SET DEFAULT '[]'::jsonb")
    op.drop_constraint(op.f('case_airflow_zones_case_product_id_zone_name_key'), 'case_airflow_zones', type_='unique')
    op.create_unique_constraint('case_airflow_zones_case_zone_key', 'case_airflow_zones', ['case_product_id', 'zone_name'])
    op.alter_column('case_slots', 'axis',
               existing_type=sa.CHAR(length=1),
               type_=sa.String(length=1),
               existing_nullable=False)
    op.execute("ALTER TABLE case_slots ALTER COLUMN affects_slots DROP DEFAULT, "
               "ALTER COLUMN affects_slots TYPE JSONB USING to_jsonb(affects_slots), "
               "ALTER COLUMN affects_slots SET DEFAULT '[]'::jsonb")
    op.drop_constraint(op.f('case_slots_case_product_id_slot_name_key'), 'case_slots', type_='unique')
    op.create_unique_constraint('case_slots_case_slot_name_key', 'case_slots', ['case_product_id', 'slot_name'])
    op.alter_column('compatibility_rules', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('component_footprints', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('curated_builds', 'is_rei',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('curated_builds', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('curated_builds', 'crowned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('curated_builds', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_curated_tier_rei'), table_name='curated_builds')
    op.alter_column('fps_estimates', 'sources',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               postgresql_using='to_jsonb(sources)')
    op.alter_column('fps_estimates', 'is_crowdsourced',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('fps_estimates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('fps_estimates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('fps_estimates_cpu_id_gpu_id_game_slug_resolution_preset_key'), 'fps_estimates', type_='unique')
    op.drop_index(op.f('idx_fps_estimates_gpucpu'), table_name='fps_estimates')
    op.create_unique_constraint('fps_estimates_cpu_gpu_game_res_preset_key', 'fps_estimates', ['cpu_id', 'gpu_id', 'game_slug', 'resolution', 'preset'])
    op.alter_column('merchants', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('offers', 'is_available',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('offers', 'last_seen_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('offers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_offers_merchant'), table_name='offers')
    op.drop_index(op.f('idx_offers_price'), table_name='offers')
    op.drop_index(op.f('idx_offers_variant'), table_name='offers')
    op.drop_constraint(op.f('offers_variant_id_merchant_id_key'), 'offers', type_='unique')
    op.create_unique_constraint('offers_variant_merchant_key', 'offers', ['variant_id', 'merchant_id'])
    op.alter_column('performance_index', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('performance_index', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_performance_product'), table_name='performance_index')
    op.drop_constraint(op.f('performance_index_product_id_benchmark_type_key'), 'performance_index', type_='unique')
    op.create_unique_constraint('performance_index_product_benchmark_key', 'performance_index', ['product_id', 'benchmark_type'])
    op.alter_column('price_history', 'is_available',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('price_history', 'recorded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_price_history_offer'), table_name='price_history')
    op.alter_column('products', 'specs',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('products', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('products', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('products', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_products_category'), table_name='products')
    op.alter_column('variants', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('variants', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('variants', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('variants', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.create_index(op.f('idx_products_category'), 'products', ['category', 'is_active'], unique=False)
    op.alter_column('products', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('products', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('products', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('products', 'specs',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.create_index(op.f('idx_price_history_offer'), 'price_history', ['offer_id', sa.literal_column('recorded_at DESC')], unique=False)
    op.alter_column('price_history', 'recorded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('price_history', 'is_available',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_constraint('performance_index_product_benchmark_key', 'performance_index', type_='unique')
    op.create_unique_constraint(op.f('performance_index_product_id_benchmark_type_key'), 'performance_index', ['product_id', 'benchmark_type'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_performance_product'), 'performance_index', ['product_id', 'benchmark_type'], unique=False)
    op.alter_column('performance_index', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('performance_index', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('offers_variant_merchant_key', 'offers', type_='unique')
    op.create_unique_constraint(op.f('offers_variant_id_merchant_id_key'), 'offers', ['variant_id', 'merchant_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_offers_variant'), 'offers', ['variant_id'], unique=False)
    op.create_index(op.f('idx_offers_price'), 'offers', ['price_brl'], unique=False)
    op.create_index(op.f('idx_offers_merchant'), 'offers', ['merchant_id'], unique=False)
    op.alter_column('offers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('offers', 'last_seen_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('offers', 'is_available',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('merchants', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_constraint('fps_estimates_cpu_gpu_game_res_preset_key', 'fps_estimates', type_='unique')
    op.create_index(op.f('idx_fps_estimates_gpucpu'), 'fps_estimates', ['gpu_id', 'cpu_id'], unique=False)
    op.create_unique_constraint(op.f('fps_estimates_cpu_id_gpu_id_game_slug_resolution_preset_key'), 'fps_estimates', ['cpu_id', 'gpu_id', 'game_slug', 'resolution', 'preset'], postgresql_nulls_not_distinct=False)
    op.alter_column('fps_estimates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('fps_estimates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('fps_estimates', 'is_crowdsourced',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('fps_estimates', 'sources',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
    op.create_index(op.f('idx_curated_tier_rei'), 'curated_builds', ['budget_tier', 'is_rei', 'is_active'], unique=False)
    op.alter_column('curated_builds', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('curated_builds', 'crowned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('curated_builds', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('curated_builds', 'is_rei',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('component_footprints', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('compatibility_rules', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_constraint('case_slots_case_slot_name_key', 'case_slots', type_='unique')
    op.create_unique_constraint(op.f('case_slots_case_product_id_slot_name_key'), 'case_slots', ['case_product_id', 'slot_name'], postgresql_nulls_not_distinct=False)
    op.alter_column('case_slots', 'affects_slots',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('case_slots', 'axis',
               existing_type=sa.String(length=1),
               type_=sa.CHAR(length=1),
               existing_nullable=False)
    op.drop_constraint('case_airflow_zones_case_zone_key', 'case_airflow_zones', type_='unique')
    op.create_unique_constraint(op.f('case_airflow_zones_case_product_id_zone_name_key'), 'case_airflow_zones', ['case_product_id', 'zone_name'], postgresql_nulls_not_distinct=False)
    op.alter_column('case_airflow_zones', 'heat_source_slots',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('case_airflow_zones', 'connects_to',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('build_sessions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('build_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('build_sessions', 'airflow_state',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('build_sessions', 'clearances',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('build_sessions', 'components',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('build_sessions', 'games',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::text[]"))
    op.drop_constraint('build_clearances_session_slot_key', 'build_clearances', type_='unique')
    op.create_unique_constraint(op.f('build_clearances_session_id_slot_name_key'), 'build_clearances', ['session_id', 'slot_name'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('build_airflow_state_session_zone_key', 'build_airflow_state', type_='unique')
    op.create_unique_constraint(op.f('build_airflow_state_session_id_zone_name_key'), 'build_airflow_state', ['session_id', 'zone_name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_clicks_offer'), 'affiliate_clicks', ['offer_id', sa.literal_column('clicked_at DESC')], unique=False)
    op.alter_column('affiliate_clicks', 'clicked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
